#ifndef TLV_IDENTITIES_H
#define TLV_IDENTITIES_H

#define MANAGEMENT 0x0001 
#define MANAGEMENT_ERROR_STATUS 0x0002 
#define ORGANIZATION_EXTENSION 0x0003 

#define REQUEST_UNICAST_TRANSMISSION 0x0004
#define GRANT_UNICAST_TRANSMISSION 0x0005
#define CANCEL_UNICAST_TRANSMISSION 0x0006
#define ACKNOWLEDGE_CANCEL_UNICAST_TRANSMISSION 0x0007

#define PATH_TRACE 0x0009

#define ALTERNATE_TIME_OFFSET_INDICATOR 0x000A 

//Security TLVs Annex K
#define AUTHENTICATION 0x2000
#define AUTHENTICATION_CHALLENGE 0x2001
#define SECURITY_ASSOCIATION_UPDATE 0x2002

//General TLV type, ID length
#define TLV_TYPE_AND_LENGTH_FIELD_LENGTH	4
#define TLV_ORGANIZATION_ID_LENGTH			3
#define TLV_ORGANIZATION_SUB_TYPE_LENGTH	3

/************************************************
* 
*      Semtech Specific TLV definition
*
*************************************************/
#define SEMTECH_ORGANIZATION_ID				0x0016C0		//Semtech company ID as assigned by IEEE

// Semtech enhanced boundary clock (BC) definition
#define SEMTECH_ORGANIZATION_SUB_TYPE_BC	0x00000			//Semtech internally defined sub-type for BC

//define SMTC_BC_USE_ACC_DELAY or not to choose Gce or Acc based eBC algorithm
//#define SMTC_BC_USE_ACC_DELAY

#define SMTC_BC_TLV_CONTROL_LENGTH			2

#ifdef SMTC_BC_USE_ACC_DELAY
#define SMTC_BC_TLV_M2S_DELAY_LENGTH		4
#define SMTC_BC_TLV_S2M_DELAY_LENGTH		4
#define SMTC_BC_TLV_DATA_LENGTH				(SMTC_BC_TLV_M2S_DELAY_LENGTH+SMTC_BC_TLV_S2M_DELAY_LENGTH)
#else
#define SMTC_BC_TLV_GCERROR_LENGTH			4
#define SMTC_BC_TLV_DATA_LENGTH				SMTC_BC_TLV_GCERROR_LENGTH
#endif

#define SMTC_BC_TLV_HEADER_LENGTH			(TLV_TYPE_AND_LENGTH_FIELD_LENGTH+TLV_ORGANIZATION_ID_LENGTH+TLV_ORGANIZATION_SUB_TYPE_LENGTH)
#define SMTC_BC_TLV_LENGTH_FIELD_VALUE		(TLV_ORGANIZATION_ID_LENGTH+TLV_ORGANIZATION_SUB_TYPE_LENGTH+SMTC_BC_TLV_CONTROL_LENGTH+SMTC_BC_TLV_DATA_LENGTH)
#define SMTC_BC_TLV_LENGTH					(TLV_TYPE_AND_LENGTH_FIELD_LENGTH+SMTC_BC_TLV_LENGTH_FIELD_VALUE)

#define SMTC_BC_TLV_TX_RATE_MASK			0x0007
#define SMTC_BC_TLV_CRYPTION_MASK			0x0018
#define SMTC_BC_TLV_NUM_FRONT_BC_MASK		0x0FE0

#define TLV_LENGTH_FIELD_OFFSET				2
#define TLV_ORGANIZATION_ID_OFFSET			TLV_TYPE_AND_LENGTH_FIELD_LENGTH
#define TLV_ORGANIZATION_SUB_TYPE_OFFSET	(TLV_ORGANIZATION_ID_OFFSET+TLV_ORGANIZATION_ID_LENGTH)
#define SMTC_BC_TLV_CONTROL_OFFSET			SMTC_BC_TLV_HEADER_LENGTH
#define SMTC_BC_TLV_DATA_OFFSET				(SMTC_BC_TLV_CONTROL_OFFSET+SMTC_BC_TLV_CONTROL_LENGTH)
#define SMTC_BC_TLV_RATE_BIT_OFFSET			0
#define SMTC_BC_TLV_CRYPTION_BIT_OFFSET		3
#define SMTC_BC_TLV_NUM_FRONT_BC_OFFSET		5

// Semtech TopSync Processor modes definitions
#define SEMTECH_ORGANIZATION_SUB_TYPE_ERROR               0x0
#define SEMTECH_ORGANIZATION_SUB_TYPE_TOPRO	              0x1        //Semtech internally defined sub-type for timestamp processor mode 2
#define SEMTECH_ORGANIZATION_SUB_TYPE_TOPRO_EXTENDED  	  0x2        //Semtech internally defined sub-type for timestamp processor mode 2
#define SMTC_TOPRO_TLV_PADDING_LENGTH			          2
#define SMTC_TOPRO_TLV_DATA_LENGTH				          4
#define SMTC_TOPRO_TLV_EXTENDED_FLAG_LENGTH               1
#define SMTC_TOPRO_TLV_EXTENDED_APPID_LENGTH              1
#define SMTC_TOPRO_TLV_EXTENDED_TIMESTAMP_FULL_ID         0
#define SMTC_TOPRO_TLV_EXTENDED_TIMESTAMP_FULL_LENGTH     12
#define SMTC_TOPRO_TLV_EXTENDED_TIMESTAMP_NANO_ID         1
#define SMTC_TOPRO_TLV_EXTENDED_TIMESTAMP_NANO_LENGTH     4
#define SMTC_TOPRO_TLV_EXTENDED_TIMESTAMP_SUBNANO_ID      2
#define SMTC_TOPRO_TLV_EXTENDED_TIMESTAMP_SUBNANO_LENGTH  8
#define SMTC_TOPRO_TLV_EXTENDED_SRC_PORT_ID_LENGTH        4
#define SMTC_TOPRO_TLV_EXTENDED_SRC_NODE_ID_LENGTH        8

#define SMTC_TOPRO_TLV_SHORT_LENGTH                       16
#define SMTC_TOPRO_TLV_LONG_MIN_LENGTH                    12

#define SMTC_TOPRO_TLV_TIME_FULL_WITH_SUB_NANOS           0
#define SMTC_TOPRO_TLV_TIME_NANOS_ONLY                    1
#define SMTC_TOPRO_TLV_TIME_NANOS_WITH_SUB_ONLY           2

//TLV for user data
#define SEMTECH_ORGANIZATION_SUB_TYPE_USER_DATA				0x000010			//Semtech internally defined sub-type for user data
#define SEMTECH_ORGANIZATION_SUB_TYPE_USER_DATA_ACK			0x000011			//Semtech internally defined sub-type for user data acknowledge
#define SEMTECH_ORGANIZATION_SUB_TYPE_USER_DATA_WORDS_LENGTH 64
#define SEMTECH_ORGANIZATION_SUB_TYPE_USER_DATA_LENGTH		(SEMTECH_ORGANIZATION_SUB_TYPE_USER_DATA_WORDS_LENGTH*4) //256
#define SEMTECH_ORGANIZATION_SUB_TYPE_USER_DATA_TLV_LENGTH	(TLV_TYPE_AND_LENGTH_FIELD_LENGTH+TLV_ORGANIZATION_ID_LENGTH+TLV_ORGANIZATION_SUB_TYPE_LENGTH+SEMTECH_ORGANIZATION_SUB_TYPE_USER_DATA_LENGTH)


//tlv for smpte
#define SMPTE_ORGANISATION_OUI			0x6897E8
#define SMPTE_ORGANISATION_SUBTYPE		0x000001




#define SmtcToProExtendedTLVGetTimestampTypeFromFlags(f) ((f) & 7)
#define SmtcToProExtendedTLVGetEpochTypeFromFlags(f)     (((f) >> 3) & 7)

#endif

